# Each route describes how an incoming URL is going to be processed by Platform.sh.
"https://{all}/":
  type: upstream
  upstream: "app:http"

"https://www.{all}/":
  type: redirect
  to: "https://{all}/"
